### ISSUE TITLE
Issues with the library

### ISSUE THREAD

**Issue by hakimio** [juny58/ion-custom-scrollbar#2]
Some issues I have noticed while looking at the library:
- Instead of [checking host element tag](https://github.com/juny58/ion-custom-scrollbar/blob/b207fa9d093ed9cb6e52cd243075f088abaaefc7/projects/ion-custom-scrollbar/src/lib/scrollbar.directive.ts#L17), you could just use `ion-content[scrollbar]` directive selector. Also, instead of `this.hostElement && this.hostElement.tagName && this.hostElement.tagName === 'ION-CONTENT'` you could have just used `this.hostElement?.tagName === 'ION-CONTENT'`
- Instead of setting [`el.innerText`](https://github.com/juny58/ion-custom-scrollbar/blob/b207fa9d093ed9cb6e52cd243075f088abaaefc7/projects/ion-custom-scrollbar/src/lib/scrollbar.directive.ts#L19), you should use `el.innerHTML`. When you set `innerText`, newlines are converted into `<br>` tags.
- [Angular Renderer](https://angular.io/api/core/Renderer2) should be used for manipulating the DOM directly:
```ts
    private createScrollbarStyleEl() {
        const hostEl: Element = this.elementRef.nativeElement,
            styleElement: HTMLStyleElement = this.renderer.createElement('style');

        this.renderer.setProperty(styleElement, 'innerHTML', this.SCROLLBAR_CSS);
        this.renderer.appendChild(hostEl.shadowRoot, styleElement);
    }
```
- Issue #1 is because you are [limiting peer dependencies to Angular v9](https://github.com/juny58/ion-custom-scrollbar/blob/b207fa9d093ed9cb6e52cd243075f088abaaefc7/projects/ion-custom-scrollbar/package.json#L5) only. Also, `tslib` dependency version should be bumped to `^2.0.0` and it should be "hard" dependency, not peer dependency.
- Might be a good idea to upgrade the project to Angular 12+ and migrate it to ["Ivy" `partial` compilation](https://angular.io/guide/creating-libraries#publishing-libraries). It would result in faster builds for people with Angular 12+, but the library would lose compatibility with older Angular versions.
- Adding `@ionic/angular` to peer dependencies might also be a good idea. Version range could be 5+: `"@ionic/angular": ">=5.0.0"`.
- Bonus: slightly nicer default custom scrollbar:
```css
::-webkit-scrollbar {
  width: 6px;
  height: 6px;
}
::-webkit-scrollbar-track {
  background-color: transparent;
}
::-webkit-scrollbar-thumb {
  background-color: #cacaca;
  border-radius: 6px;
}

::-webkit-scrollbar-thumb:hover {
  background-color: #aaa;
}
.inner-scroll {
  scrollbar-width: thin
  scrollbar-color: #cacaca transparent;
}
```
